### PR TITLE
Add support for UNION ALL

### PR DESCRIPTION
**Pull request by tpaulshippy**
Same as #17 but includes a test.

Also did this: https://github.com/vlado/activerecord-cte/pull/17#issuecomment-1972001187

### CODE REVIEW

**Comment by tpaulshippy** [comment]
Now I see https://github.com/rails/rails/pull/51601 will kind of make this gem obsolete. But we are not quite ready to move to 7.2 so this could still be useful for us.

**Comment by vlado** [comment]
Thanks @tpaulshippy, can you check failing workflows? Maybe you can match just the union all part in sql and that results are as expected.

**Comment by vlado** [comment]
@tpaulshippy Please check what is wrong with ruby setup step in pg workflow. Once fixed I will merge it.

**Comment by tpaulshippy** [comment]
I'm not sure how to get the postgres to be accessible from the tests. Seems weird because it appears to be following [the docs](https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/creating-postgresql-service-containers) and we do this same thing [in our rails builds](https://github.com/StrongMind/public-reusable-workflows/blob/8c5d81e341fe52fe336581ddf4eae118802d5a5e/.github/workflows/docker-build.yml#L70) also.

**Comment by vlado** [comment]
@tpaulshippy Should we remove changes in pg workflow file? https://github.com/vlado/activerecord-cte/pull/18/files#diff-192f4dfa0de6d7b1c66e5951cd9d74135c175381cbfb6f59d09133560cd1e098

**Comment by vlado** [comment]
@tpaulshippy Should we remove changes in pg workflow file? https://github.com/vlado/activerecord-cte/pull/18/files#diff-192f4dfa0de6d7b1c66e5951cd9d74135c175381cbfb6f59d09133560cd1e098

@tpaulshippy I've just tested that in https://github.com/vlado/activerecord-cte/pull/20 and it works. Please revert the changes in pg workflow and I will merge this PR.

**Comment by vlado** [comment]
Thanks @tpaulshippy, version 0.4.0 relased.

**Pull request merged**
